version: '2'
services:
 neo4j:
  image: neo4j:3.5.3
  environment:
   - NEO4J_AUTH=neo4j/supersecret
   - NEO4J_HEAP_MEMORY=2048 
   - NEO4J_CACHE_MEMORY=1G 
  volumes:
   - ./db/dbms:/data/dbms 
  ports: 
   - 7474:7474 
   - 7687:7687
